// <auto-generated />
using Catalog.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catalog.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220601212815_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("KodotiCatalog")
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("Decimal");

                    b.HasKey("ProductId");

                    b.ToTable("Products", "KodotiCatalog");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "Description for product 001",
                            Name = "Product 001",
                            Price = 896m
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Description for product 002",
                            Name = "Product 002",
                            Price = 950m
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Description for product 003",
                            Name = "Product 003",
                            Price = 557m
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "Description for product 004",
                            Name = "Product 004",
                            Price = 252m
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "Description for product 005",
                            Name = "Product 005",
                            Price = 737m
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "Description for product 006",
                            Name = "Product 006",
                            Price = 237m
                        },
                        new
                        {
                            ProductId = 7,
                            Description = "Description for product 007",
                            Name = "Product 007",
                            Price = 678m
                        },
                        new
                        {
                            ProductId = 8,
                            Description = "Description for product 008",
                            Name = "Product 008",
                            Price = 381m
                        },
                        new
                        {
                            ProductId = 9,
                            Description = "Description for product 009",
                            Name = "Product 009",
                            Price = 283m
                        },
                        new
                        {
                            ProductId = 10,
                            Description = "Description for product 010",
                            Name = "Product 010",
                            Price = 976m
                        },
                        new
                        {
                            ProductId = 11,
                            Description = "Description for product 011",
                            Name = "Product 011",
                            Price = 793m
                        },
                        new
                        {
                            ProductId = 12,
                            Description = "Description for product 012",
                            Name = "Product 012",
                            Price = 543m
                        },
                        new
                        {
                            ProductId = 13,
                            Description = "Description for product 013",
                            Name = "Product 013",
                            Price = 935m
                        },
                        new
                        {
                            ProductId = 14,
                            Description = "Description for product 014",
                            Name = "Product 014",
                            Price = 494m
                        },
                        new
                        {
                            ProductId = 15,
                            Description = "Description for product 015",
                            Name = "Product 015",
                            Price = 391m
                        },
                        new
                        {
                            ProductId = 16,
                            Description = "Description for product 016",
                            Name = "Product 016",
                            Price = 289m
                        },
                        new
                        {
                            ProductId = 17,
                            Description = "Description for product 017",
                            Name = "Product 017",
                            Price = 383m
                        },
                        new
                        {
                            ProductId = 18,
                            Description = "Description for product 018",
                            Name = "Product 018",
                            Price = 583m
                        },
                        new
                        {
                            ProductId = 19,
                            Description = "Description for product 019",
                            Name = "Product 019",
                            Price = 437m
                        },
                        new
                        {
                            ProductId = 20,
                            Description = "Description for product 020",
                            Name = "Product 020",
                            Price = 796m
                        },
                        new
                        {
                            ProductId = 21,
                            Description = "Description for product 021",
                            Name = "Product 021",
                            Price = 432m
                        },
                        new
                        {
                            ProductId = 22,
                            Description = "Description for product 022",
                            Name = "Product 022",
                            Price = 833m
                        },
                        new
                        {
                            ProductId = 23,
                            Description = "Description for product 023",
                            Name = "Product 023",
                            Price = 725m
                        },
                        new
                        {
                            ProductId = 24,
                            Description = "Description for product 024",
                            Name = "Product 024",
                            Price = 158m
                        },
                        new
                        {
                            ProductId = 25,
                            Description = "Description for product 025",
                            Name = "Product 025",
                            Price = 736m
                        },
                        new
                        {
                            ProductId = 26,
                            Description = "Description for product 026",
                            Name = "Product 026",
                            Price = 224m
                        },
                        new
                        {
                            ProductId = 27,
                            Description = "Description for product 027",
                            Name = "Product 027",
                            Price = 600m
                        },
                        new
                        {
                            ProductId = 28,
                            Description = "Description for product 028",
                            Name = "Product 028",
                            Price = 580m
                        },
                        new
                        {
                            ProductId = 29,
                            Description = "Description for product 029",
                            Name = "Product 029",
                            Price = 195m
                        },
                        new
                        {
                            ProductId = 30,
                            Description = "Description for product 030",
                            Name = "Product 030",
                            Price = 503m
                        },
                        new
                        {
                            ProductId = 31,
                            Description = "Description for product 031",
                            Name = "Product 031",
                            Price = 564m
                        },
                        new
                        {
                            ProductId = 32,
                            Description = "Description for product 032",
                            Name = "Product 032",
                            Price = 396m
                        },
                        new
                        {
                            ProductId = 33,
                            Description = "Description for product 033",
                            Name = "Product 033",
                            Price = 414m
                        },
                        new
                        {
                            ProductId = 34,
                            Description = "Description for product 034",
                            Name = "Product 034",
                            Price = 988m
                        },
                        new
                        {
                            ProductId = 35,
                            Description = "Description for product 035",
                            Name = "Product 035",
                            Price = 972m
                        },
                        new
                        {
                            ProductId = 36,
                            Description = "Description for product 036",
                            Name = "Product 036",
                            Price = 609m
                        },
                        new
                        {
                            ProductId = 37,
                            Description = "Description for product 037",
                            Name = "Product 037",
                            Price = 693m
                        },
                        new
                        {
                            ProductId = 38,
                            Description = "Description for product 038",
                            Name = "Product 038",
                            Price = 641m
                        },
                        new
                        {
                            ProductId = 39,
                            Description = "Description for product 039",
                            Name = "Product 039",
                            Price = 884m
                        },
                        new
                        {
                            ProductId = 40,
                            Description = "Description for product 040",
                            Name = "Product 040",
                            Price = 593m
                        },
                        new
                        {
                            ProductId = 41,
                            Description = "Description for product 041",
                            Name = "Product 041",
                            Price = 336m
                        },
                        new
                        {
                            ProductId = 42,
                            Description = "Description for product 042",
                            Name = "Product 042",
                            Price = 630m
                        },
                        new
                        {
                            ProductId = 43,
                            Description = "Description for product 043",
                            Name = "Product 043",
                            Price = 682m
                        },
                        new
                        {
                            ProductId = 44,
                            Description = "Description for product 044",
                            Name = "Product 044",
                            Price = 639m
                        },
                        new
                        {
                            ProductId = 45,
                            Description = "Description for product 045",
                            Name = "Product 045",
                            Price = 294m
                        },
                        new
                        {
                            ProductId = 46,
                            Description = "Description for product 046",
                            Name = "Product 046",
                            Price = 199m
                        },
                        new
                        {
                            ProductId = 47,
                            Description = "Description for product 047",
                            Name = "Product 047",
                            Price = 309m
                        },
                        new
                        {
                            ProductId = 48,
                            Description = "Description for product 048",
                            Name = "Product 048",
                            Price = 467m
                        },
                        new
                        {
                            ProductId = 49,
                            Description = "Description for product 049",
                            Name = "Product 049",
                            Price = 841m
                        },
                        new
                        {
                            ProductId = 50,
                            Description = "Description for product 050",
                            Name = "Product 050",
                            Price = 510m
                        },
                        new
                        {
                            ProductId = 51,
                            Description = "Description for product 051",
                            Name = "Product 051",
                            Price = 723m
                        },
                        new
                        {
                            ProductId = 52,
                            Description = "Description for product 052",
                            Name = "Product 052",
                            Price = 249m
                        },
                        new
                        {
                            ProductId = 53,
                            Description = "Description for product 053",
                            Name = "Product 053",
                            Price = 298m
                        },
                        new
                        {
                            ProductId = 54,
                            Description = "Description for product 054",
                            Name = "Product 054",
                            Price = 632m
                        },
                        new
                        {
                            ProductId = 55,
                            Description = "Description for product 055",
                            Name = "Product 055",
                            Price = 763m
                        },
                        new
                        {
                            ProductId = 56,
                            Description = "Description for product 056",
                            Name = "Product 056",
                            Price = 603m
                        },
                        new
                        {
                            ProductId = 57,
                            Description = "Description for product 057",
                            Name = "Product 057",
                            Price = 954m
                        },
                        new
                        {
                            ProductId = 58,
                            Description = "Description for product 058",
                            Name = "Product 058",
                            Price = 210m
                        },
                        new
                        {
                            ProductId = 59,
                            Description = "Description for product 059",
                            Name = "Product 059",
                            Price = 966m
                        },
                        new
                        {
                            ProductId = 60,
                            Description = "Description for product 060",
                            Name = "Product 060",
                            Price = 105m
                        },
                        new
                        {
                            ProductId = 61,
                            Description = "Description for product 061",
                            Name = "Product 061",
                            Price = 617m
                        },
                        new
                        {
                            ProductId = 62,
                            Description = "Description for product 062",
                            Name = "Product 062",
                            Price = 256m
                        },
                        new
                        {
                            ProductId = 63,
                            Description = "Description for product 063",
                            Name = "Product 063",
                            Price = 486m
                        },
                        new
                        {
                            ProductId = 64,
                            Description = "Description for product 064",
                            Name = "Product 064",
                            Price = 552m
                        },
                        new
                        {
                            ProductId = 65,
                            Description = "Description for product 065",
                            Name = "Product 065",
                            Price = 671m
                        },
                        new
                        {
                            ProductId = 66,
                            Description = "Description for product 066",
                            Name = "Product 066",
                            Price = 604m
                        },
                        new
                        {
                            ProductId = 67,
                            Description = "Description for product 067",
                            Name = "Product 067",
                            Price = 490m
                        },
                        new
                        {
                            ProductId = 68,
                            Description = "Description for product 068",
                            Name = "Product 068",
                            Price = 206m
                        },
                        new
                        {
                            ProductId = 69,
                            Description = "Description for product 069",
                            Name = "Product 069",
                            Price = 896m
                        },
                        new
                        {
                            ProductId = 70,
                            Description = "Description for product 070",
                            Name = "Product 070",
                            Price = 449m
                        },
                        new
                        {
                            ProductId = 71,
                            Description = "Description for product 071",
                            Name = "Product 071",
                            Price = 376m
                        },
                        new
                        {
                            ProductId = 72,
                            Description = "Description for product 072",
                            Name = "Product 072",
                            Price = 242m
                        },
                        new
                        {
                            ProductId = 73,
                            Description = "Description for product 073",
                            Name = "Product 073",
                            Price = 535m
                        },
                        new
                        {
                            ProductId = 74,
                            Description = "Description for product 074",
                            Name = "Product 074",
                            Price = 594m
                        },
                        new
                        {
                            ProductId = 75,
                            Description = "Description for product 075",
                            Name = "Product 075",
                            Price = 508m
                        },
                        new
                        {
                            ProductId = 76,
                            Description = "Description for product 076",
                            Name = "Product 076",
                            Price = 222m
                        },
                        new
                        {
                            ProductId = 77,
                            Description = "Description for product 077",
                            Name = "Product 077",
                            Price = 426m
                        },
                        new
                        {
                            ProductId = 78,
                            Description = "Description for product 078",
                            Name = "Product 078",
                            Price = 657m
                        },
                        new
                        {
                            ProductId = 79,
                            Description = "Description for product 079",
                            Name = "Product 079",
                            Price = 954m
                        },
                        new
                        {
                            ProductId = 80,
                            Description = "Description for product 080",
                            Name = "Product 080",
                            Price = 391m
                        },
                        new
                        {
                            ProductId = 81,
                            Description = "Description for product 081",
                            Name = "Product 081",
                            Price = 245m
                        },
                        new
                        {
                            ProductId = 82,
                            Description = "Description for product 082",
                            Name = "Product 082",
                            Price = 227m
                        },
                        new
                        {
                            ProductId = 83,
                            Description = "Description for product 083",
                            Name = "Product 083",
                            Price = 233m
                        },
                        new
                        {
                            ProductId = 84,
                            Description = "Description for product 084",
                            Name = "Product 084",
                            Price = 106m
                        },
                        new
                        {
                            ProductId = 85,
                            Description = "Description for product 085",
                            Name = "Product 085",
                            Price = 107m
                        },
                        new
                        {
                            ProductId = 86,
                            Description = "Description for product 086",
                            Name = "Product 086",
                            Price = 243m
                        },
                        new
                        {
                            ProductId = 87,
                            Description = "Description for product 087",
                            Name = "Product 087",
                            Price = 572m
                        },
                        new
                        {
                            ProductId = 88,
                            Description = "Description for product 088",
                            Name = "Product 088",
                            Price = 658m
                        },
                        new
                        {
                            ProductId = 89,
                            Description = "Description for product 089",
                            Name = "Product 089",
                            Price = 477m
                        },
                        new
                        {
                            ProductId = 90,
                            Description = "Description for product 090",
                            Name = "Product 090",
                            Price = 192m
                        },
                        new
                        {
                            ProductId = 91,
                            Description = "Description for product 091",
                            Name = "Product 091",
                            Price = 667m
                        },
                        new
                        {
                            ProductId = 92,
                            Description = "Description for product 092",
                            Name = "Product 092",
                            Price = 444m
                        },
                        new
                        {
                            ProductId = 93,
                            Description = "Description for product 093",
                            Name = "Product 093",
                            Price = 759m
                        },
                        new
                        {
                            ProductId = 94,
                            Description = "Description for product 094",
                            Name = "Product 094",
                            Price = 863m
                        },
                        new
                        {
                            ProductId = 95,
                            Description = "Description for product 095",
                            Name = "Product 095",
                            Price = 171m
                        },
                        new
                        {
                            ProductId = 96,
                            Description = "Description for product 096",
                            Name = "Product 096",
                            Price = 277m
                        },
                        new
                        {
                            ProductId = 97,
                            Description = "Description for product 097",
                            Name = "Product 097",
                            Price = 153m
                        },
                        new
                        {
                            ProductId = 98,
                            Description = "Description for product 098",
                            Name = "Product 098",
                            Price = 168m
                        },
                        new
                        {
                            ProductId = 99,
                            Description = "Description for product 099",
                            Name = "Product 099",
                            Price = 557m
                        },
                        new
                        {
                            ProductId = 100,
                            Description = "Description for product 100",
                            Name = "Product 100",
                            Price = 798m
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.Property<int>("ProductInStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductInStockId"), 1L, 1);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductInStockId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Stocks", "KodotiCatalog");

                    b.HasData(
                        new
                        {
                            ProductInStockId = 1,
                            ProductId = 1,
                            Stock = 43
                        },
                        new
                        {
                            ProductInStockId = 2,
                            ProductId = 2,
                            Stock = 50
                        },
                        new
                        {
                            ProductInStockId = 3,
                            ProductId = 3,
                            Stock = 92
                        },
                        new
                        {
                            ProductInStockId = 4,
                            ProductId = 4,
                            Stock = 75
                        },
                        new
                        {
                            ProductInStockId = 5,
                            ProductId = 5,
                            Stock = 54
                        },
                        new
                        {
                            ProductInStockId = 6,
                            ProductId = 6,
                            Stock = 68
                        },
                        new
                        {
                            ProductInStockId = 7,
                            ProductId = 7,
                            Stock = 51
                        },
                        new
                        {
                            ProductInStockId = 8,
                            ProductId = 8,
                            Stock = 37
                        },
                        new
                        {
                            ProductInStockId = 9,
                            ProductId = 9,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 10,
                            ProductId = 10,
                            Stock = 27
                        },
                        new
                        {
                            ProductInStockId = 11,
                            ProductId = 11,
                            Stock = 63
                        },
                        new
                        {
                            ProductInStockId = 12,
                            ProductId = 12,
                            Stock = 35
                        },
                        new
                        {
                            ProductInStockId = 13,
                            ProductId = 13,
                            Stock = 41
                        },
                        new
                        {
                            ProductInStockId = 14,
                            ProductId = 14,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 15,
                            ProductId = 15,
                            Stock = 39
                        },
                        new
                        {
                            ProductInStockId = 16,
                            ProductId = 16,
                            Stock = 38
                        },
                        new
                        {
                            ProductInStockId = 17,
                            ProductId = 17,
                            Stock = 37
                        },
                        new
                        {
                            ProductInStockId = 18,
                            ProductId = 18,
                            Stock = 78
                        },
                        new
                        {
                            ProductInStockId = 19,
                            ProductId = 19,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 20,
                            ProductId = 20,
                            Stock = 24
                        },
                        new
                        {
                            ProductInStockId = 21,
                            ProductId = 21,
                            Stock = 90
                        },
                        new
                        {
                            ProductInStockId = 22,
                            ProductId = 22,
                            Stock = 65
                        },
                        new
                        {
                            ProductInStockId = 23,
                            ProductId = 23,
                            Stock = 44
                        },
                        new
                        {
                            ProductInStockId = 24,
                            ProductId = 24,
                            Stock = 94
                        },
                        new
                        {
                            ProductInStockId = 25,
                            ProductId = 25,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 26,
                            ProductId = 26,
                            Stock = 83
                        },
                        new
                        {
                            ProductInStockId = 27,
                            ProductId = 27,
                            Stock = 41
                        },
                        new
                        {
                            ProductInStockId = 28,
                            ProductId = 28,
                            Stock = 56
                        },
                        new
                        {
                            ProductInStockId = 29,
                            ProductId = 29,
                            Stock = 37
                        },
                        new
                        {
                            ProductInStockId = 30,
                            ProductId = 30,
                            Stock = 90
                        },
                        new
                        {
                            ProductInStockId = 31,
                            ProductId = 31,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 32,
                            ProductId = 32,
                            Stock = 69
                        },
                        new
                        {
                            ProductInStockId = 33,
                            ProductId = 33,
                            Stock = 89
                        },
                        new
                        {
                            ProductInStockId = 34,
                            ProductId = 34,
                            Stock = 66
                        },
                        new
                        {
                            ProductInStockId = 35,
                            ProductId = 35,
                            Stock = 55
                        },
                        new
                        {
                            ProductInStockId = 36,
                            ProductId = 36,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 37,
                            ProductId = 37,
                            Stock = 55
                        },
                        new
                        {
                            ProductInStockId = 38,
                            ProductId = 38,
                            Stock = 69
                        },
                        new
                        {
                            ProductInStockId = 39,
                            ProductId = 39,
                            Stock = 93
                        },
                        new
                        {
                            ProductInStockId = 40,
                            ProductId = 40,
                            Stock = 34
                        },
                        new
                        {
                            ProductInStockId = 41,
                            ProductId = 41,
                            Stock = 44
                        },
                        new
                        {
                            ProductInStockId = 42,
                            ProductId = 42,
                            Stock = 28
                        },
                        new
                        {
                            ProductInStockId = 43,
                            ProductId = 43,
                            Stock = 54
                        },
                        new
                        {
                            ProductInStockId = 44,
                            ProductId = 44,
                            Stock = 80
                        },
                        new
                        {
                            ProductInStockId = 45,
                            ProductId = 45,
                            Stock = 40
                        },
                        new
                        {
                            ProductInStockId = 46,
                            ProductId = 46,
                            Stock = 70
                        },
                        new
                        {
                            ProductInStockId = 47,
                            ProductId = 47,
                            Stock = 69
                        },
                        new
                        {
                            ProductInStockId = 48,
                            ProductId = 48,
                            Stock = 61
                        },
                        new
                        {
                            ProductInStockId = 49,
                            ProductId = 49,
                            Stock = 93
                        },
                        new
                        {
                            ProductInStockId = 50,
                            ProductId = 50,
                            Stock = 62
                        },
                        new
                        {
                            ProductInStockId = 51,
                            ProductId = 51,
                            Stock = 99
                        },
                        new
                        {
                            ProductInStockId = 52,
                            ProductId = 52,
                            Stock = 25
                        },
                        new
                        {
                            ProductInStockId = 53,
                            ProductId = 53,
                            Stock = 82
                        },
                        new
                        {
                            ProductInStockId = 54,
                            ProductId = 54,
                            Stock = 77
                        },
                        new
                        {
                            ProductInStockId = 55,
                            ProductId = 55,
                            Stock = 96
                        },
                        new
                        {
                            ProductInStockId = 56,
                            ProductId = 56,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 57,
                            ProductId = 57,
                            Stock = 91
                        },
                        new
                        {
                            ProductInStockId = 58,
                            ProductId = 58,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 59,
                            ProductId = 59,
                            Stock = 69
                        },
                        new
                        {
                            ProductInStockId = 60,
                            ProductId = 60,
                            Stock = 23
                        },
                        new
                        {
                            ProductInStockId = 61,
                            ProductId = 61,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 62,
                            ProductId = 62,
                            Stock = 97
                        },
                        new
                        {
                            ProductInStockId = 63,
                            ProductId = 63,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 64,
                            ProductId = 64,
                            Stock = 44
                        },
                        new
                        {
                            ProductInStockId = 65,
                            ProductId = 65,
                            Stock = 54
                        },
                        new
                        {
                            ProductInStockId = 66,
                            ProductId = 66,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 67,
                            ProductId = 67,
                            Stock = 26
                        },
                        new
                        {
                            ProductInStockId = 68,
                            ProductId = 68,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 69,
                            ProductId = 69,
                            Stock = 57
                        },
                        new
                        {
                            ProductInStockId = 70,
                            ProductId = 70,
                            Stock = 39
                        },
                        new
                        {
                            ProductInStockId = 71,
                            ProductId = 71,
                            Stock = 31
                        },
                        new
                        {
                            ProductInStockId = 72,
                            ProductId = 72,
                            Stock = 91
                        },
                        new
                        {
                            ProductInStockId = 73,
                            ProductId = 73,
                            Stock = 80
                        },
                        new
                        {
                            ProductInStockId = 74,
                            ProductId = 74,
                            Stock = 80
                        },
                        new
                        {
                            ProductInStockId = 75,
                            ProductId = 75,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 76,
                            ProductId = 76,
                            Stock = 81
                        },
                        new
                        {
                            ProductInStockId = 77,
                            ProductId = 77,
                            Stock = 40
                        },
                        new
                        {
                            ProductInStockId = 78,
                            ProductId = 78,
                            Stock = 42
                        },
                        new
                        {
                            ProductInStockId = 79,
                            ProductId = 79,
                            Stock = 97
                        },
                        new
                        {
                            ProductInStockId = 80,
                            ProductId = 80,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 81,
                            ProductId = 81,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 82,
                            ProductId = 82,
                            Stock = 8
                        },
                        new
                        {
                            ProductInStockId = 83,
                            ProductId = 83,
                            Stock = 45
                        },
                        new
                        {
                            ProductInStockId = 84,
                            ProductId = 84,
                            Stock = 53
                        },
                        new
                        {
                            ProductInStockId = 85,
                            ProductId = 85,
                            Stock = 20
                        },
                        new
                        {
                            ProductInStockId = 86,
                            ProductId = 86,
                            Stock = 91
                        },
                        new
                        {
                            ProductInStockId = 87,
                            ProductId = 87,
                            Stock = 91
                        },
                        new
                        {
                            ProductInStockId = 88,
                            ProductId = 88,
                            Stock = 89
                        },
                        new
                        {
                            ProductInStockId = 89,
                            ProductId = 89,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 90,
                            ProductId = 90,
                            Stock = 38
                        },
                        new
                        {
                            ProductInStockId = 91,
                            ProductId = 91,
                            Stock = 52
                        },
                        new
                        {
                            ProductInStockId = 92,
                            ProductId = 92,
                            Stock = 67
                        },
                        new
                        {
                            ProductInStockId = 93,
                            ProductId = 93,
                            Stock = 53
                        },
                        new
                        {
                            ProductInStockId = 94,
                            ProductId = 94,
                            Stock = 47
                        },
                        new
                        {
                            ProductInStockId = 95,
                            ProductId = 95,
                            Stock = 97
                        },
                        new
                        {
                            ProductInStockId = 96,
                            ProductId = 96,
                            Stock = 67
                        },
                        new
                        {
                            ProductInStockId = 97,
                            ProductId = 97,
                            Stock = 50
                        },
                        new
                        {
                            ProductInStockId = 98,
                            ProductId = 98,
                            Stock = 69
                        },
                        new
                        {
                            ProductInStockId = 99,
                            ProductId = 99,
                            Stock = 36
                        },
                        new
                        {
                            ProductInStockId = 100,
                            ProductId = 100,
                            Stock = 86
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.HasOne("Catalog.Domain.Product", null)
                        .WithOne("Stock")
                        .HasForeignKey("Catalog.Domain.ProductInStock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Navigation("Stock")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
