// <auto-generated />
using Customer.Persistance.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Customer.Persistance.Database.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    partial class CustomerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("KodotiCustomer")
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Customer.Domain.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients", "KodotiCustomer");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Name = "Client 001"
                        },
                        new
                        {
                            ClientId = 2,
                            Name = "Client 002"
                        },
                        new
                        {
                            ClientId = 3,
                            Name = "Client 003"
                        },
                        new
                        {
                            ClientId = 4,
                            Name = "Client 004"
                        },
                        new
                        {
                            ClientId = 5,
                            Name = "Client 005"
                        },
                        new
                        {
                            ClientId = 6,
                            Name = "Client 006"
                        },
                        new
                        {
                            ClientId = 7,
                            Name = "Client 007"
                        },
                        new
                        {
                            ClientId = 8,
                            Name = "Client 008"
                        },
                        new
                        {
                            ClientId = 9,
                            Name = "Client 009"
                        },
                        new
                        {
                            ClientId = 10,
                            Name = "Client 010"
                        },
                        new
                        {
                            ClientId = 11,
                            Name = "Client 011"
                        },
                        new
                        {
                            ClientId = 12,
                            Name = "Client 012"
                        },
                        new
                        {
                            ClientId = 13,
                            Name = "Client 013"
                        },
                        new
                        {
                            ClientId = 14,
                            Name = "Client 014"
                        },
                        new
                        {
                            ClientId = 15,
                            Name = "Client 015"
                        },
                        new
                        {
                            ClientId = 16,
                            Name = "Client 016"
                        },
                        new
                        {
                            ClientId = 17,
                            Name = "Client 017"
                        },
                        new
                        {
                            ClientId = 18,
                            Name = "Client 018"
                        },
                        new
                        {
                            ClientId = 19,
                            Name = "Client 019"
                        },
                        new
                        {
                            ClientId = 20,
                            Name = "Client 020"
                        },
                        new
                        {
                            ClientId = 21,
                            Name = "Client 021"
                        },
                        new
                        {
                            ClientId = 22,
                            Name = "Client 022"
                        },
                        new
                        {
                            ClientId = 23,
                            Name = "Client 023"
                        },
                        new
                        {
                            ClientId = 24,
                            Name = "Client 024"
                        },
                        new
                        {
                            ClientId = 25,
                            Name = "Client 025"
                        },
                        new
                        {
                            ClientId = 26,
                            Name = "Client 026"
                        },
                        new
                        {
                            ClientId = 27,
                            Name = "Client 027"
                        },
                        new
                        {
                            ClientId = 28,
                            Name = "Client 028"
                        },
                        new
                        {
                            ClientId = 29,
                            Name = "Client 029"
                        },
                        new
                        {
                            ClientId = 30,
                            Name = "Client 030"
                        },
                        new
                        {
                            ClientId = 31,
                            Name = "Client 031"
                        },
                        new
                        {
                            ClientId = 32,
                            Name = "Client 032"
                        },
                        new
                        {
                            ClientId = 33,
                            Name = "Client 033"
                        },
                        new
                        {
                            ClientId = 34,
                            Name = "Client 034"
                        },
                        new
                        {
                            ClientId = 35,
                            Name = "Client 035"
                        },
                        new
                        {
                            ClientId = 36,
                            Name = "Client 036"
                        },
                        new
                        {
                            ClientId = 37,
                            Name = "Client 037"
                        },
                        new
                        {
                            ClientId = 38,
                            Name = "Client 038"
                        },
                        new
                        {
                            ClientId = 39,
                            Name = "Client 039"
                        },
                        new
                        {
                            ClientId = 40,
                            Name = "Client 040"
                        },
                        new
                        {
                            ClientId = 41,
                            Name = "Client 041"
                        },
                        new
                        {
                            ClientId = 42,
                            Name = "Client 042"
                        },
                        new
                        {
                            ClientId = 43,
                            Name = "Client 043"
                        },
                        new
                        {
                            ClientId = 44,
                            Name = "Client 044"
                        },
                        new
                        {
                            ClientId = 45,
                            Name = "Client 045"
                        },
                        new
                        {
                            ClientId = 46,
                            Name = "Client 046"
                        },
                        new
                        {
                            ClientId = 47,
                            Name = "Client 047"
                        },
                        new
                        {
                            ClientId = 48,
                            Name = "Client 048"
                        },
                        new
                        {
                            ClientId = 49,
                            Name = "Client 049"
                        },
                        new
                        {
                            ClientId = 50,
                            Name = "Client 050"
                        },
                        new
                        {
                            ClientId = 51,
                            Name = "Client 051"
                        },
                        new
                        {
                            ClientId = 52,
                            Name = "Client 052"
                        },
                        new
                        {
                            ClientId = 53,
                            Name = "Client 053"
                        },
                        new
                        {
                            ClientId = 54,
                            Name = "Client 054"
                        },
                        new
                        {
                            ClientId = 55,
                            Name = "Client 055"
                        },
                        new
                        {
                            ClientId = 56,
                            Name = "Client 056"
                        },
                        new
                        {
                            ClientId = 57,
                            Name = "Client 057"
                        },
                        new
                        {
                            ClientId = 58,
                            Name = "Client 058"
                        },
                        new
                        {
                            ClientId = 59,
                            Name = "Client 059"
                        },
                        new
                        {
                            ClientId = 60,
                            Name = "Client 060"
                        },
                        new
                        {
                            ClientId = 61,
                            Name = "Client 061"
                        },
                        new
                        {
                            ClientId = 62,
                            Name = "Client 062"
                        },
                        new
                        {
                            ClientId = 63,
                            Name = "Client 063"
                        },
                        new
                        {
                            ClientId = 64,
                            Name = "Client 064"
                        },
                        new
                        {
                            ClientId = 65,
                            Name = "Client 065"
                        },
                        new
                        {
                            ClientId = 66,
                            Name = "Client 066"
                        },
                        new
                        {
                            ClientId = 67,
                            Name = "Client 067"
                        },
                        new
                        {
                            ClientId = 68,
                            Name = "Client 068"
                        },
                        new
                        {
                            ClientId = 69,
                            Name = "Client 069"
                        },
                        new
                        {
                            ClientId = 70,
                            Name = "Client 070"
                        },
                        new
                        {
                            ClientId = 71,
                            Name = "Client 071"
                        },
                        new
                        {
                            ClientId = 72,
                            Name = "Client 072"
                        },
                        new
                        {
                            ClientId = 73,
                            Name = "Client 073"
                        },
                        new
                        {
                            ClientId = 74,
                            Name = "Client 074"
                        },
                        new
                        {
                            ClientId = 75,
                            Name = "Client 075"
                        },
                        new
                        {
                            ClientId = 76,
                            Name = "Client 076"
                        },
                        new
                        {
                            ClientId = 77,
                            Name = "Client 077"
                        },
                        new
                        {
                            ClientId = 78,
                            Name = "Client 078"
                        },
                        new
                        {
                            ClientId = 79,
                            Name = "Client 079"
                        },
                        new
                        {
                            ClientId = 80,
                            Name = "Client 080"
                        },
                        new
                        {
                            ClientId = 81,
                            Name = "Client 081"
                        },
                        new
                        {
                            ClientId = 82,
                            Name = "Client 082"
                        },
                        new
                        {
                            ClientId = 83,
                            Name = "Client 083"
                        },
                        new
                        {
                            ClientId = 84,
                            Name = "Client 084"
                        },
                        new
                        {
                            ClientId = 85,
                            Name = "Client 085"
                        },
                        new
                        {
                            ClientId = 86,
                            Name = "Client 086"
                        },
                        new
                        {
                            ClientId = 87,
                            Name = "Client 087"
                        },
                        new
                        {
                            ClientId = 88,
                            Name = "Client 088"
                        },
                        new
                        {
                            ClientId = 89,
                            Name = "Client 089"
                        },
                        new
                        {
                            ClientId = 90,
                            Name = "Client 090"
                        },
                        new
                        {
                            ClientId = 91,
                            Name = "Client 091"
                        },
                        new
                        {
                            ClientId = 92,
                            Name = "Client 092"
                        },
                        new
                        {
                            ClientId = 93,
                            Name = "Client 093"
                        },
                        new
                        {
                            ClientId = 94,
                            Name = "Client 094"
                        },
                        new
                        {
                            ClientId = 95,
                            Name = "Client 095"
                        },
                        new
                        {
                            ClientId = 96,
                            Name = "Client 096"
                        },
                        new
                        {
                            ClientId = 97,
                            Name = "Client 097"
                        },
                        new
                        {
                            ClientId = 98,
                            Name = "Client 098"
                        },
                        new
                        {
                            ClientId = 99,
                            Name = "Client 099"
                        },
                        new
                        {
                            ClientId = 100,
                            Name = "Client 100"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
